name: arrow_escape
description: Arrow Escape - A casual grid puzzle game where you slide arrows out of the grid.
publish_to: 'none'
version: 1.3.3+17

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Game Engine
  flame: ^1.18.0
  flame_audio: ^2.10.0

  # Ads
  google_mobile_ads: ^5.1.0
  unity_ads_plugin: ^0.4.0

  # State Management
  provider: ^6.1.2

  # Persistence
  shared_preferences: ^2.3.2

  # UI & Animations
  google_fonts: ^6.2.1

  confetti: ^0.7.0
  flutter_animate: ^4.5.0

  # Audio


  # Utils
  collection: ^1.18.0
  intl: ^0.19.0
  package_info_plus: ^8.1.2
  url_launcher: ^6.3.0
  lucide_icons_flutter: ^3.1.14+2
  in_app_update: ^5.0.0
  flutter_dotenv: ^6.0.1

  # Firebase
  firebase_core: ^3.15.0
  firebase_crashlytics: ^4.3.10
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/audio/
    - assets/fonts/
    - assets/levels.bin
    - assets/PNG_Levels/
    - assets/PNG_Levels/10x10/
    - assets/PNG_Levels/15x15/
    - assets/PNG_Levels/25x25/
    - assets/PNG_Levels/30x30/
    - assets/PNG_Levels/40x40/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FAF6F0"
  adaptive_icon_foreground: "assets/images/logo.png"
